# Generated by Django 6.0 on 2025-12-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.TextField()),
                ("p256dh", models.CharField(max_length=255)),
                ("auth", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Push subscription",
                "verbose_name_plural": "Push subscriptions",
            },
        ),
        migrations.CreateModel(
            name="TemperatureRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                ("temperature", models.FloatField(verbose_name="Temperature (°C)")),
                (
                    "weather",
                    models.CharField(
                        choices=[
                            ("sunny", "Sunny"),
                            ("few_clouds", "Few clouds"),
                            ("cloudy", "Cloudy"),
                            ("rain", "Rain"),
                            ("snow", "Snow"),
                        ],
                        max_length=20,
                        verbose_name="Weather",
                    ),
                ),
                ("wind", models.BooleanField(default=False, verbose_name="Wind")),
                ("hail", models.BooleanField(default=False, verbose_name="Hail")),
                ("mist", models.BooleanField(default=False, verbose_name="Mist")),
                (
                    "snow_cm",
                    models.FloatField(blank=True, null=True, verbose_name="Snow (cm)"),
                ),
                (
                    "rain_mm",
                    models.FloatField(blank=True, null=True, verbose_name="Rain (mm)"),
                ),
                (
                    "max_temp",
                    models.FloatField(blank=True, null=True, verbose_name="Maximal temperature (°C)"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "weight_kg",
                    models.FloatField(blank=True, null=True, verbose_name="Weight (kg)"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
            ],
            options={
                "verbose_name": "Temperature record",
                "verbose_name_plural": "Temperature records",
                "ordering": ["-date"],
            },
        ),
    ]
