# Generated by Django 6.0 on 2025-12-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("temps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Snooze",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.TextField(unique=True, verbose_name="Endpoint")),
                ("snooze_until", models.DateTimeField(verbose_name="Snooze until")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Snooze",
                "verbose_name_plural": "Snoozes",
            },
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="auth",
            field=models.CharField(max_length=255, verbose_name="Auth key"),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="endpoint",
            field=models.TextField(unique=True, verbose_name="Endpoint"),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="p256dh",
            field=models.CharField(max_length=255, verbose_name="p256dh key"),
        ),
    ]
